library(readr)
add<-read.csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/admission/train.csv")
View(add)
head(add,10)           #gives first 10 rows of dataset

tail(add,10)   #gives last 10 rows of a dataset
install.packages('dplyr')
library(dplyr)
add %>% summarise_each(funs(mean))             #gives mean of all the columns at the same time
median(add$GRE.Score)         			#gives median of the colums of our dataset
median(add$TOEFL.Score)
require(modeest)      				#gives mode of the column of the datset
mfv(add$SOP)
cor(add$GRE.Score,add$TOEFL.Score)
library(ggplot2)				# gives the scatter plot for the above correlation for better visualization
  ggplot(add)    +                                             
          aes(x=add$GRE.Score,y=add$TOEFL.Score)+
          geom_point(colour="#0c4c8a")+
         theme_minimal()
  pairs(add[,c(2,3,7,9)])  				#gives pairwiseplot for the columns of dataset
  require(corrplot)              							#gives heat map for columns of dataset
  corrplot(cor(add[,c(1,2,3,4,5,6,7,8,9)]),method= "number",type="lower")
  hist(add$GRE.Score,breaks = 20,main = "Histogram")    			#plotting a histogram for the grescore and its frequency
  d_1<-rchisq(add$CGPA,df=7)						#gives historam for the random samples generated by chisq from the cgpa
  hist(d_1,freq = FALSE,breaks = 50) 
  x<-d_1 									#we plot a histogram and compare it to the probability density function of the ??2-distribution with df=7							
    hist(d_1, 
                              breaks = 50, 
                              freq = FALSE, 
                              main = ('Histogram for chi square distribution '))
    curve(dchisq(x, df = 7), from = 0, to = 15, n = 5000, col= 'orange', lwd=2, add = T) 
    d_2<-rt(add$CGPA,df=10)      						#we plot a histogram and compare it to the probability density function of the t-distribution with df=10                                          
     hist(d_2,freq = FALSE,breaks=50) 
     x<-d_2 
     hist(d_2, 
                               breaks = 50, 
                                freq = FALSE, 
                              main = ('Histogram for t distribution '))
     curve(dt(x, df = 10), from = -4, to = 4, n = 5000, col= 'orange', lwd=2, add = T) 
     contour_plot<-function(x,y)
     {
       mu1<-mean(x)
       mu2<-mean(y)
       mu3<-c(mu1,mu2)
       c1<-cor(x,y)
       s1<-sqrt(var(x))
       s2<-sqrt(var(y))
       sigma1<-matrix(c(s1,c1,c1,s2),ncol = 2)
       library(MASS)
       bivn<-mvrnorm(100000,mu=mu3,Sigma = sigma1)
       head(bivn)
       bivn.kde<-kde2d(bivn[,1],bivn[,2],n=50)
       contour(bivn.kde,col="red")
     }  
     contour_plot(add$GRE.Score,add$TOEFL.Score)
     
     perspec_plot<-function(x,y)
     {
       mu1<-mean(x)
       mu2<-mean(y)
       mu3<-c(mu1,mu2)
       c1<-cor(x,y)
       s1<-sqrt(var(x))
       s2<-sqrt(var(y))
       sigma1<-matrix(c(s1,c1,c1,s2),ncol = 2)
       library(MASS)
       bivn<-mvrnorm(100000,mu=mu3,Sigma = sigma1)
       head(bivn)
       bivn.kde<-kde2d(bivn[,1],bivn[,2],n=50)
       persp(bivn.kde, theta = 200, phi = 20, 
             shade = 0.75, col = "light blue", expand = 0.5, r = 2, 
             ltheta = 240, ticktype = "detailed")
     }  
     perspec_plot(add$GRE.Score,add$TOEFL.Score)
     
     cd_normalsigma_unknown<-function(n,alpha)
        {
           mu<-mean(n)
            s=sqrt(var(n))
            len1<-length(n)
            z1<-qt(1-(alpha/2),df=((len1)-1))
            f1<-(mu-(z1*(s/sqrt(len1))))
            f2<-(mu+(z1*(s/sqrt(len1))))
            f<-c(f1,f2)
            return(f)       
       }
     null_hypothesis<-function(samp,a,alpha)
     {
       xbar<-mean(samp)
       s<-sqrt(var(samp))
       len1<-length(samp)
       z_stat<-qt(1-(alpha/2),df=((len1)-1))
       z1<-(xbar-a)*sqrt(len1)/s
       if(abs(z1)<=z_stat){
         print("Hyptothesis is in acceptance region")
       }else{
         print("Hypothesis is in rejectance region")
       }
     }
     null_hypothesis(add$GRE.Score,545.36,0.05)
     install.packages('tidyverse')
     library(tidyverse)
     library(ggpubr)
     ggplot(add,aes(x=CGPA,y=Chance.of.Admit))+
         geom_point()+
        stat_smooth(method = lm)
     model<-lm(Chance.of.Admit~CGPA,data=add)
     model
     
     new.cgpa<-data.frame(CGPA=c(5.64,9.99,3.65))
     predict(model,newdata = new.cgpa)
     
     confint(model)
     
     pred.int<-predict(model,interval="prediction")
     mydata<-cbind(add,pred.int)
     
     p<-ggplot(mydata,aes(CGPA,Chance.of.Admit))+
       geom_point()+
        stat_smooth(method=lm)
      p+geom_line(aes(y=lwr),color="red", linetype="dashed")+
        geom_line(aes(y=upr),color="red", linetype="dashed")
     